Update the stale vif-vrouter code
Signed-off-by: Anirban Chakraborty <abchak@juniper.net>

diff --git a/vif-vrouter b/vif-vrouter
--- a/vif-vrouter
+++ b/vif-vrouter
@@ -83,16 +83,19 @@ add_vm_interface()
 	exit 1
     fi
 
-    local vmi=$(echo ${config} | tr ';' '\n' | awk '/iface-id:/ {print $2;}' 2>/dev/null)
+    local vmi=$(echo ${config} | tr ';' '\n' | awk '/nicira-iface-id:/ {print $2;}' 2>/dev/null)
     if [ -z "${vmi}" ]; then
 	logger -t scripts-vif "Unable to find virtual-machine-interface uuid"
 	exit 1
     fi
 
-    local vm=$(echo ${config} | tr ';' '\n' | awk '/vm-id:/ {print $2;}' 2>/dev/null)
+    local vm=$(echo ${config} | tr ';' '\n' | awk '/cloudstack-vm-id:/ {print $2;}' 2>/dev/null)
     if [ -z "${vm}" ]; then
-	logger -t scripts-vif "Unable to find virtual-machine uuid"
-	exit 1
+	vm=$(echo ${config} | tr ';' '\n' | awk '/nicira-vm-id:/ {print $2;}' 2>/dev/null)
+	if [ -z  "${vm}" ]; then
+	    logger -t scripts-vif "Unable to find virtual-machine uuid"
+	    exit 1
+	fi
     fi
 
     local guestmac=$(xenstore-read "/local/domain/$DOMID/device/vif/$DEVID/mac" 2>/dev/null)
